services:
  - type: web
    name: filhet-allard-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py --port 8000 --host 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
    autoDeploy: true

  - type: web
    name: filhet-allard-admin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python admin.py
    envVars:
      - key: MONGO_URI
        sync: false
    autoDeploy: true
